spring:
  profiles:
    active: -dev

---
#权限管理配置
spring:
  profiles: authority
  application:
    name: cloud-authority-dev
  #数据源配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    #driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/authority?characterEncoding=utf-8
    username: root
    password:
#mybatis配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.xt.pojo

---
#测试配置
spring:
  profiles: test
  application:
    name: cloud-config-test
